# Generated by Django 3.2.5 on 2021-07-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna_sequence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnasequence',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
