# Generated by Django 3.2.5 on 2021-08-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dna_sequence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnasequence',
            name='sequence_type',
        ),
    ]
