# Generated by Django 3.2.5 on 2021-07-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna_sequence', '0002_dnasequence_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnasequence',
            name='seq',
            field=models.TextField(default=''),
        ),
    ]
