# Generated by Django 3.2.5 on 2021-08-06 19:32

from django.db import migrations, models
import django.db.models.manager
import dna_sequence.models


class Migration(migrations.Migration):

    dependencies = [
        ('dna_sequence', '0004_auto_20210806_1511'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='proteinsequence',
            managers=[
                ('sequences', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='proteinsequence',
            name='fasta_header',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='proteinsequence',
            name='raw_sequence',
            field=models.TextField(default='', validators=[dna_sequence.models.validate_sequence]),
        ),
    ]
