# Generated by Django 3.2.5 on 2021-08-18 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dna_sequence', '0006_auto_20210813_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastaSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.CharField(default='', max_length=1000)),
                ('seq_type', models.CharField(choices=[('D', 'dna'), ('R', 'rna'), ('P', 'peptide')], default='D', max_length=10)),
                ('header', models.CharField(max_length=1000, verbose_name='')),
                ('accession', models.CharField(max_length=50, verbose_name='')),
                ('organism', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenBankAnnotationSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecule_type', models.CharField(max_length=50, verbose_name='')),
                ('topology', models.CharField(max_length=50, verbose_name='')),
                ('date', models.CharField(max_length=50, verbose_name='')),
                ('gi', models.CharField(max_length=50, verbose_name='')),
                ('organism', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GenBankSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.CharField(default='', max_length=1000)),
                ('seq_type', models.CharField(choices=[('D', 'dna'), ('R', 'rna'), ('P', 'peptide')], default='D', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='proteinsequence',
            name='user',
        ),
        migrations.DeleteModel(
            name='DNASequence',
        ),
        migrations.DeleteModel(
            name='ProteinSequence',
        ),
        migrations.AddField(
            model_name='genbankannotationset',
            name='seq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dna_sequence.genbanksequence'),
        ),
    ]
