# Generated by Django 3.2.5 on 2021-08-18 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dna_sequence', '0007_auto_20210818_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.TextField(default='')),
                ('input_file_format', models.CharField(max_length=50, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.CharField(default='', max_length=1000)),
                ('seq_type', models.CharField(choices=[('D', 'dna'), ('R', 'rna'), ('P', 'peptide')], default='D', max_length=10)),
                ('header', models.CharField(default='', max_length=1000)),
                ('accession', models.CharField(default='', max_length=50)),
                ('organism', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='genbanksequence',
            name='user',
        ),
        migrations.RemoveField(
            model_name='genbankannotationset',
            name='gi',
        ),
        migrations.AddField(
            model_name='genbankannotationset',
            name='accession',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='genbankannotationset',
            name='definition',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='genbankannotationset',
            name='features',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='genbankannotationset',
            name='keywords',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='genbankannotationset',
            name='locus',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='genbankannotationset',
            name='source',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='genbankannotationset',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='genbankannotationset',
            name='molecule_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='genbankannotationset',
            name='organism',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='genbankannotationset',
            name='topology',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='FastaSequence',
        ),
        migrations.AlterField(
            model_name='genbankannotationset',
            name='seq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dna_sequence.sequence'),
        ),
        migrations.DeleteModel(
            name='GenBankSequence',
        ),
    ]
