# Generated by Django 3.2.5 on 2021-08-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna_sequence', '0008_auto_20210818_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='notes',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='genbankannotationset',
            name='accession',
        ),
        migrations.RemoveField(
            model_name='genbankannotationset',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='genbankannotationset',
            name='features',
        ),
        migrations.RemoveField(
            model_name='genbankannotationset',
            name='locus',
        ),
        migrations.RemoveField(
            model_name='genbankannotationset',
            name='seq',
        ),
        migrations.AddField(
            model_name='genbankannotationset',
            name='accessions',
            field=models.JSONField(default=str),
        ),
        migrations.AddField(
            model_name='genbankannotationset',
            name='data_file_division',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='genbankannotationset',
            name='gi',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='genbankannotationset',
            name='references',
            field=models.JSONField(default=str),
        ),
        migrations.AddField(
            model_name='genbankannotationset',
            name='sequence_version',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genbankannotationset',
            name='taxonomy',
            field=models.JSONField(default=str),
        ),
        migrations.AlterField(
            model_name='genbankannotationset',
            name='date',
            field=models.DateField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='genbankannotationset',
            name='keywords',
            field=models.JSONField(default=str),
        ),
        migrations.AlterField(
            model_name='genbankannotationset',
            name='organism',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='genbankannotationset',
            name='source',
            field=models.CharField(default='', max_length=100),
        ),
    ]
