# Generated by Django 3.2.5 on 2021-08-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna_sequence', '0009_auto_20210819_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genbankannotationset',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
