# Generated by Django 3.2.5 on 2021-08-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dna_sequence', '0010_alter_genbankannotationset_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genbankannotationset',
            name='references',
        ),
    ]
