# Generated by Django 3.2.5 on 2021-08-26 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dna_sequence', '0014_alter_genbankannotationset_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
                ('feature_type', models.CharField(default='', max_length=50)),
                ('note', models.CharField(default='', max_length=1000)),
                ('db_xref', models.JSONField(default=str)),
                ('sequence', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='dna_sequence.sequence')),
            ],
        ),
    ]
